# Generated by Django 4.1.7 on 2023-03-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("third_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default=None, max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=128),
        ),
    ]
